<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameTranslationLauncher.Domain\GameTranslationLauncher.Domain.csproj" />
    <ProjectReference Include="..\GameTranslationLauncher.Application\GameTranslationLauncher.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
